### ISSUE TITLE
Download Issue

### ISSUE THREAD

**Issue by Hilbekale** [StefanMaron/synXLIFF#1]
Hi,

i have tried to download the extension, but it is not working in IE or Opera.

Thanks.

**Comment by StefanMaron** [comment]
I just checked the download in Opera and it works for me. You need to type in your E-Mail address and the download link will be sent to you.

Do you have problems regarding the E-Mail or the direct Download?

**Comment by Hilbekale** [comment]
I believe a browser addon blocks the little popup on my site. It works in a clean browser.
