### ISSUE TITLE
Import of new *.g.xlf should update existing languages

### ISSUE THREAD

**Issue by larswestman** [StefanMaron/synXLIFF#13]
If I import a new *.g.xlf where a new field has been added with the same caption as an existing the already imported languages should be updated. The last line below should have got "Transport" as translation. Maybe the status should be set to "Review" or something simliar and before export the could be a warning if X lines has status = Review and Y lines has status = New.

Simliar if I update an already existing translation I should get a question like "There are X other lines with the same source text.\\Do you want to update these?" Of course only in the same language as I'm currently editing.

![2018-12-13_13-29-15](https://user-images.githubusercontent.com/43792551/49938838-58729f80-fedb-11e8-85dd-c97682efacfe.jpg)

**Comment by larswestman** [comment]
This also (I think) has the effect that if VS Code generates a new trans.unit ID for a caption my existing translations are gone. This happened to me when renaming names for groups and actions because I had forgot my prefix for some.

**Comment by StefanMaron** [comment]
If the trans.unit ID changes we can not update the existing translation since we cannot get any connection. It also could be a new item while you deleted the old one.
