### ISSUE TITLE
Feature: Tranlation from Standardtranslation

### ISSUE THREAD

**Issue by hey84** [StefanMaron/synXLIFF#16]
I have imported our tranlationexcelsheet into the "synXLIFF Default Translation"-table and now iam searching for a possibilty to translate the records in "synXLIFF Translation" with this dictionary.

**Comment by StefanMaron** [comment]
The default translations are used when a new phrase to translate is inserted. 

If you want to use the new default translations for a whole project. You can simply delete tho project and import the "*.g.xlf" file once again. 

If you need to save already translated phrases you can first export the translation in your target language. This file you can import later on to restore your already translated phrases (after importing the global file).

I hope this is understandable :)

**Comment by hey84** [comment]
Nice, works perfect! Thank You :)
