### ISSUE TITLE
An error occurred while sending the request.

### ISSUE THREAD

**Issue by fvet** [StefanMaron/synXLIFF#17]
HI,

Just downloaded an installed the extension, but when trying to navigate to the Xliff projects, I get an 'An error occurred while sending the request.' error? Any hints?

**Comment by StefanMaron** [comment]
We currently have problems with our webservice which is responsible for checking for a new version. As a temporary fix you can go to the synXLIFF Setup and disable the automatic checking. Then you should be able to use the extension normally
