### ISSUE TITLE
The 'al-object-target' attribute is not declared

### ISSUE THREAD

**Issue by larswestman** [StefanMaron/synXLIFF#24]
I get this error when trying to import an xlf file: Imported XML cannot validate with the schema: The 'al-object-target' attribute is not declared.

![image](https://user-images.githubusercontent.com/43792551/64408760-d2f5d780-d087-11e9-9a68-b0de00f4a2ac.png)
[LogTrade Connect.g.zip](https://github.com/StefanMaron/synXLIFF/files/3582667/LogTrade.Connect.g.zip)

BC15.0.35903.0-se
al-4.0.170493.vsix

I would really appriciate if you could prioritize this since it's a blocker for the BC15 version of our app.

Thanks!

**Comment by StefanMaron** [comment]
Do you know if this attribute is important for vs code in the translated xlf file? Currently i do not have a fall release container available so i cant test it myself

**Comment by larswestman** [comment]
VS Code creates that attribute for page- and table extensions so the import needs to handle it at least. It looks as it's a reference to the ID of the page or table that the extension extends. It's not the object ID though. It's the trans-unit-id. Since VS Code creates this my guess is that you need to do it as well.

I think you need to keep track on the project if it's before platform 4.0 or if it's 4.0 or later. This means that you would need to create the project first (and setup the new option field that determines format) and _after_ that do the import so the correct xml port can run (I guess you need a separate xml-port since the layout has changed).

**Comment by larswestman** [comment]
I attached an example as a zip file in my original post so you can try that file

**Comment by larswestman** [comment]
Worked like charm. Thanks!
