### ISSUE TITLE
The remote certificate is invalid according to the validation procedure

### ISSUE THREAD

**Issue by larswestman** [StefanMaron/synXLIFF#9]
Often when i open the list of projects I get this error message. Only in RTC so far, but I haven't run synXLIFF in the web client that much yet. If I restart the RTC it works. Also if I refresh in the address bar.

![2018-12-13_08-10-16](https://user-images.githubusercontent.com/43792551/49921862-32cfa100-feaf-11e8-90ea-8d62faa1822b.jpg)

This is parts of what Fiddler catches of that call:

CONNECT synbc.table.core.windows.net:443 HTTP/1.1
Host: synbc.table.core.windows.net

**Comment by larswestman** [comment]
I'm not sure this is an issue. It could be me having Fiddler active and disturbing https traffic. But why is there any traffic over the nic when opening the list? Does it call home or something?

**Comment by StefanMaron** [comment]
synXLIFF checks once per day if a new version is available. If you dont like this you can deactivate this in the synxliff setup.

**Comment by larswestman** [comment]
Aha. And since it must have been Fiddler causing this you can close this ticket.

Thank's for the good work you put into this. synXLIFF has been great help for us translating. I setup a server and simply invited the translator to that server so he could work directly in the BC client with it. No more excel spreadsheets!
